env:
  global:
    - CC_TEST_REPORTER_ID=4c74221fe8816404035072a02c9b7379200f6c47e2759f6ccd1d55cf77ee9f64

language: php

php:
  - '7.2'

sudo: false

before_install:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: composer test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
    on_success: never
    on_failure: always